### ISSUE TITLE
Installation with Ansible

### ISSUE THREAD

**Issue by citronalco** [schlangenprogrammiernacht/spn-meta#10]
I've created an Ansible role for installing this on Debian 10, see https://git.bingo-ev.de/geierb/spn-ansible

It works for me, maybe it's useful for others, too. I would be glad if you would add the link in spn-meta's Readme.md.

**Comment by cfr34k** [comment]
Thanks!

I have added a new section “External Contributions” with your link to the README. Is that ok for you?

**Comment by citronalco** [comment]
Sure, thanks!
