### ISSUE TITLE
Highscore is reset

### ISSUE THREAD

**Issue by noppelmax** [schlangenprogrammiernacht/spn-meta#16]
Hey,

i figured out that sometimes the highscores reset? Is this wanted behaviour, because more snake spawn in the environment? My gameserver process is only 9hrs old, but the server is running for over 24hrs. May this be the reason for the reset? (Is the highscore only saved in ram?)

Kind regards and THANKS! SPN is awesome!

**Comment by cfr34k** [comment]
Hi,

that’s actually on purpose and scores older than 24h are not considered in the highscore list by default. You can tune that time in https://github.com/schlangenprogrammiernacht/website/blob/master/Programmierspiel/settings.py#L112 . In any case, all scores are stored in the database forever, so if you increase the mentioned variable, old highscores will reappear.

The idea is that game conditions change over time as new players join and old highscores are therefore no longer comparable (or simply unreachable with more players).

> Kind regards and THANKS! SPN is awesome!

Thanks. I'm glad you like it :)

**Comment by noppelmax** [comment]
Alright! Thank you! Read this a year ago already. I close this issue.
