### ISSUE TITLE
Python environment couldn't import Django

### ISSUE THREAD

**Issue by M4tse** [schlangenprogrammiernacht/spn-meta#19]
When I try to execute `./manage.py collectstatic` it throws an Error:  `sudo ./manage.py collectstatic
  File "./manage.py", line 14
    ) from exc
         ^
SyntaxError: invalid syntax
`
So after that I tried to use python3, but then it throws me an ImportError: ` Couldn't import Django. Are you sure it's installed and available on your PYTHONPATH environment variable? Did you forget to activate a virtual environment?`
I even checked if the package is installed.

**Comment by cfr34k** [comment]
Hi, this looks like you are trying to run `manage.py` from the wrong environment. Normally, there is a Python virtual environment set up by the [build.sh script](https://github.com/schlangenprogrammiernacht/spn-meta/blob/ce66c3ae45655c05e8aa169c7483fdf67922abea/build.sh). The virtual environment contains the correct Python version (Python 3) and all the dependencies from [requirements.txt](https://github.com/schlangenprogrammiernacht/website/blob/ed1d9e6ea19e0eaab66993ccfd15a08df3fc2120/requirements.txt). Did you activate the virtual environment before `./manage.py collectstatic` as shown [in the README](https://github.com/schlangenprogrammiernacht/spn-meta/blob/master/README.md#static-files)?

If the virtual environment (`website/env`) does not exist, try creating and activating it as follows:

```bash
cd website
python3 -m venv env
source env/bin/activate
pip install -r requirements.txt
./manage.py collectstatic
```

**Comment by M4tse** [comment]
I am just stupid I forgot to give it sufficient permissions
