### ISSUE TITLE
gameserver.core_userprofile doesnt exist

### ISSUE THREAD

**Issue by noppelmax** [schlangenprogrammiernacht/spn-meta#4]
Hey,

we tried to install the schlangenprogrammiernacht for a local event. But stuck running the gameserver with the following error:
```
terminate called after throwing an instance of "sql::SQLException" what(): Table "gameserver.core_userprofile" doesnt exist.   ./helper_scripts/run_gameserver.sh: line 4
```

Do you have any idea what we may have done wrong? We run `./dev_build.sh` and expected it to create all the tables.

Kind regards,
nopx

**Comment by noppelmax** [comment]
I think we got it. You should use the same DB and DB-Credentials for local-settings.py and the gameserver. In the default configs is written "gameserver" and in "local-setting.py" it is called "snake". Also it seems like on the defaults from Environment.h is used.

Regards,
nopx

**Comment by xieve** [comment]
Yep, I just documented this in my PR. I think you can close this issue.

**Comment by cfr34k** [comment]
Hi nopx,

yes, the defaults are different in the gameserver’s `Environment.h` and the website’s `local_settings.py`, which I have to admit is confusing. However, as you have to manually set up a DB user, there can't be a sensible default and you have to change both files anyway.

The gameserver can also read the database settings from environment variables if you don't want to edit `Environment.h`.

When both files are updated, you can run `dev_build.sh` which compiles all programs and applies the Django migrations to the database (creating all necessary tables).

Kind regards,
cfr34k
