### ISSUE TITLE
Shared Memory Problem

### ISSUE THREAD

**Issue by noppelmax** [schlangenprogrammiernacht/spn-meta#6]
Hey,

i tried to setup a SPN server. I updated the submodules in https://github.com/Bytewerk/spn-docker to the latest version. And the docker builds run through. But by running i get the following error:

```
Attaching to spn-docker_database_1, spn-docker_website_1, spn-docker_gameserver_1, spn-docker_relayserver_1, spn-docker_proxy_1
gameserver_1   | Cannot write to shared memory located at /mnt/spn_shm/ !
spn-docker_gameserver_1 exited with code 1
```

Is it still possible to run the servers in separated docker containers? Do you have any instruction how to setup a system?

Kind regards,
Max

**Comment by cfr34k** [comment]
Hi Max,

it seems you're mixing repositories from the old GPN18 version with sandboxed bots written in Lua and the GPN19 version with bots written in C++ running in Docker containers. https://github.com/Bytewerk/spn-docker is a repository from the old version.

I'm sorry for the confusion. Maybe I should archive the old repositories to make this more clear. Please do only use repositories from https://github.com/schlangenprogrammiernacht when you set up SPN19.

There are currently no scripts or instructions to run the gameserver itself in a Docker container. SPN19 uses Docker to isolate the bots, so I'm not sure what a good setup for running the gameserver itself in Docker would look like. This would require nesting of Docker containers. If you find a way to do that, please document it. I think many people would be interested.

Some setup instructions for a normal system (running the gameserver on the host) are in [README.md](https://github.com/schlangenprogrammiernacht/spn-meta/blob/master/README.md). I'll check if they are up to date.

Kind regards,
Thomas

**Comment by cfr34k** [comment]
@noppelmax I have overhauled the README. Please let me know if it works for you.

**Comment by noppelmax** [comment]
I'm still on this topic. Just got other things to work on the last days. Will notice you, when I got problems setting it up. :) Thanks!

**Comment by noppelmax** [comment]
Hey, I succeed to setup the system. :) Nice work! Thanks a lot!
